POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Mikä on kun ei onnistu",
  "author": "Aatos",
  "url": "https://www.aatos.com/mikä-on-kun-ei-onnistu",
  "likes": 100000
}